import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { notificationProvider, RefineSnackbarProvider } from "@refinedev/mui";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <GitHubBanner />
          <ColorModeContextProvider defaultMode={defaultMode}>
            <RefineSnackbarProvider>
              <DevtoolsProvider>
                <Refine
                  authProvider={authProviderClient}
                  dataProvider={dataProvider}
                  notificationProvider={notificationProvider}
                  resources={[
                    {
                      name: "profile",
                      list: "/profile",
                      create: "/profile/create",
                      edit: "/profile/edit/:id",
                      show: "/profile/show/:id",
                    },
                  ]}
                  options={{
                    syncWithLocation: true,
                    warnWhenUnsavedChanges: true,
                    useNewQueryKeys: true,
                    projectId: "kjgbR1-y8gG2L-MC2Fl7",
                    title: { text: "Refine Project", icon: <AppIcon /> },
                  }}
                >
                  {children}
                </Refine>
              </DevtoolsProvider>
            </RefineSnackbarProvider>
          </ColorModeContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
